version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Manage Go package versions.
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
